package com.isoler.studyim.business.userroom.model.bean;

import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.TableField;

import com.isoler.studyim.common.model.bean.BaseEntity;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;

/**
 * <p>
 * 用户聊天室关联表
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-07-28
 */
@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
@TableName("db_chat.t_user_room")
@ApiModel(value="UserRoom对象", description="用户聊天室关联表")
public class UserRoom extends BaseEntity {

    @ApiModelProperty(value = "聊天室id")
    @TableField("c_chat_room_id")
    private String chatRoomId;

    @ApiModelProperty(value = "用户id")
    @TableField("c_user_id")
    private String userId;

    @ApiModelProperty(value = "用户类型（1: 群主 2. 管理员 3. 群员)")
    @TableField("c_user_type")
    private String userType;



}
