package com.isoler.studyim.business.filestorage.controller;


import com.isoler.studyim.business.filestorage.model.dto.FileUploadDto;
import com.isoler.studyim.business.filestorage.model.dto.FileUploadResultDto;
import com.isoler.studyim.business.filestorage.service.IFileStorageService;
import com.isoler.studyim.common.api.CommonResult;
import io.swagger.annotations.ApiOperation;
import org.springframework.web.bind.annotation.*;

import javax.annotation.Resource;

/**
 * <p>
 * 前端控制器
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-10-02
 */
@RestController
@RequestMapping("file")
public class FileStorageController {

    @Resource
    private IFileStorageService fileStorageService;

    /**
     * 下载文件
     *
     * @param id
     */
    @GetMapping("{id}")
    @ApiOperation("下载文件")
    public void downloadFile(@PathVariable("id") String id) {

    }

    /**
     * 上传文件
     * @param dto
     * @return
     */
    @PostMapping("")
    @ApiOperation("上传文件")
    public CommonResult<FileUploadResultDto> uploadFile(FileUploadDto dto) {
        return null;
    }

    /**
     * 删除文件
     * @param id
     * @return
     */
    @DeleteMapping("{id}")
    @ApiOperation("删除文件")
    public CommonResult<String> deleteFile(@PathVariable("id") String id) {
        return null;
    }

}
