package com.isoler.studyim.business.user.service.impl;

import com.isoler.studyim.business.user.model.bean.SysUser;
import com.isoler.studyim.business.user.mapper.SysUserMapper;
import com.isoler.studyim.business.user.service.ISysUserService;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import org.springframework.stereotype.Service;

/**
 * <p>
 * 系统用户表 服务实现类
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-07-28
 */
@Service
public class SysUserServiceImpl extends ServiceImpl<SysUserMapper, SysUser> implements ISysUserService {

}
