package com.isoler.studyim.business.userroom.service;

import com.isoler.studyim.business.userroom.model.bean.UserRoom;
import com.baomidou.mybatisplus.extension.service.IService;

/**
 * <p>
 * 用户聊天室关联表 服务类
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-07-28
 */
public interface IUserRoomService extends IService<UserRoom> {

}
