package com.isoler.studyim.business.filestorage.mapper;

import com.isoler.studyim.business.filestorage.model.bean.FileStorage;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;

/**
 * <p>
 *  Mapper 接口
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-10-02
 */
public interface FileStorageMapper extends BaseMapper<FileStorage> {

}
