package com.isoler.studyim.business.user.service;

import com.isoler.studyim.business.user.model.bean.SysUser;
import com.baomidou.mybatisplus.extension.service.IService;

/**
 * <p>
 * 系统用户表 服务类
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-07-28
 */
public interface ISysUserService extends IService<SysUser> {

}
