package com.isoler.studyim.business.user.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.isoler.studyim.business.user.model.bean.SysUser;
import com.isoler.studyim.business.user.model.dto.UserDto;

/**
 * <p>
 * 系统用户表 服务类
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-07-28
 */
public interface ISysUserService extends IService<SysUser> {
    /**
     * 根据用户名获取用户信息
     *
     * @param username
     * @return
     */
    SysUser getByUserName(String username);

    /**
     * 注册用户
     *
     * @param dto
     * @return
     */
    SysUser register(UserDto dto);
}
