package com.isoler.studyim.business.filestorage.model.bean;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableName;
import com.isoler.studyim.common.model.bean.BaseEntityExt;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;

import java.time.LocalDateTime;

/**
 * <p>
 * 
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-10-02
 */
@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
@TableName("db_chat.t_file_storage")
@ApiModel(value="FileStorage对象", description="")
public class FileStorage extends BaseEntityExt {


    @ApiModelProperty(value = "文件名")
    @TableField("c_file_name")
    private String fileName;

    @ApiModelProperty(value = "文件协议")
    @TableField("c_file_protocol")
    private String fileProtocol;

    @ApiModelProperty(value = "文件大小")
    @TableField("n_file_size")
    private Long fileSize;

    @ApiModelProperty(value = "文件md5")
    @TableField("c_file_md5")
    private String fileMd5;

    @ApiModelProperty(value = "文件过期时间")
    @TableField("dt_expire_time")
    private LocalDateTime expireTime;


    @ApiModelProperty(value = "文件排序号")
    @TableField("n_order")
    private Integer xh;

}
