spring:
  thymeleaf:
    cache: false
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          password: 123456
          username: sa
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://127.0.0.1:5432/isoler
      lazy: true

# minio 存储配置
minio:
  endpoint: http://127.0.0.1:8001
  accessKey: admin
  secretKey: 12345678Aa
  storageId: s3
  bucket-name: im-bucket
  pre-path: storage

# 定时任务配置
schdule:
  clean-file:
    # 每天凌晨清理过期文件
    cron: 0 0 0 * * ?