spring:
  thymeleaf:
    cache: false
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          password: 123456
          username: sa
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://43.138.159.130:5432/isoler
      lazy: true

# minio 存储配置
minio:
  endpoint: http://43.138.159.130:8001
  accessKey: admin
  secretKey: 12345678Aa
  storageId: s3
  bucket-name: im-bucket
  pre-path: storage

# 定时任务配置
schedule:
  clean-file:
    # 每天凌晨12点清理过期文件
    cron: 0 0 0 * * ?
  invalid-message:
    # 每天凌晨1点清理过期文件
    cron: 0 0 1 * * ?
  clean-message:
    # 每天凌晨2点清理过期文件
    cron: 0 0 2 * * ?

# 打印错误信息堆栈
server:
  error:
    include-stacktrace: always
    include-exception: true