package com.isoler.studyim.business.chatroom.service.impl;

import com.isoler.studyim.business.chatroom.model.bean.ChatRoom;
import com.isoler.studyim.business.chatroom.mapper.ChatRoomMapper;
import com.isoler.studyim.business.chatroom.service.IChatRoomService;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import org.springframework.stereotype.Service;

/**
 * <p>
 * 聊天室 服务实现类
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-07-28
 */
@Service
public class ChatRoomServiceImpl extends ServiceImpl<ChatRoomMapper, ChatRoom> implements IChatRoomService {

}
