package com.isoler.studyim.business.chatmessage.service;

import com.isoler.studyim.business.chatmessage.model.bean.ChatMessage;
import com.baomidou.mybatisplus.extension.service.IService;

/**
 * <p>
 * 聊天消息 服务类
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-07-28
 */
public interface IChatMessageService extends IService<ChatMessage> {

}
