package com.isoler.studyim.business.chatmessage.service;

import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.baomidou.mybatisplus.extension.service.IService;
import com.isoler.studyim.business.chatmessage.model.bean.ChatMessage;
import com.isoler.studyim.business.chatmessage.model.dto.ChatMessageDto;
import com.isoler.studyim.business.chatmessage.model.dto.ChatMessagePageDto;

import java.time.LocalDateTime;
import java.util.List;

/**
 * <p>
 * 聊天消息 服务类
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-07-28
 */
public interface IChatMessageService extends IService<ChatMessage> {
    /**
     * 让消息失效
     */
    void invalidMessage();

    /**
     * 清理消息
     *
     * @param localDateTime
     */
    void cleanMessage(LocalDateTime localDateTime);

    /**
     * 发送广播消息
     *
     * @param chatMessage
     */
    void sendPublicMessage(ChatMessage chatMessage);

    /**
     * 查询消息列表-分页
     *
     * @param dto 参数
     * @return
     */
    Page<ChatMessage> pageChatMessage(ChatMessagePageDto dto);

    /**
     * 查询消息列表
     *
     * @param dto 参数
     * @return
     */
    List<ChatMessage> listChatMessage(ChatMessageDto dto);

}
