package com.isoler.studyim.business.chatroom.mapper;

import com.isoler.studyim.business.chatroom.model.bean.ChatRoom;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;

/**
 * <p>
 * 聊天室 Mapper 接口
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-07-28
 */
public interface ChatRoomMapper extends BaseMapper<ChatRoom> {

}
