package com.isoler.studyim.business.chatroom.service;

import com.isoler.studyim.business.chatroom.model.bean.ChatRoom;
import com.baomidou.mybatisplus.extension.service.IService;

/**
 * <p>
 * 聊天室 服务类
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-07-28
 */
public interface IChatRoomService extends IService<ChatRoom> {

}
