package com.isoler.studyim.business.user.controller;


import com.isoler.studyim.business.user.model.bean.SysUser;
import com.isoler.studyim.common.api.CommonResult;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * <p>
 * 系统用户表 前端控制器
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-07-28
 */
@RestController
@RequestMapping("user")
public class SysUserController {

    @GetMapping("name")
    public CommonResult<SysUser> getCurrentUser(Authentication authentication) {
        SysUser user = (SysUser) authentication.getPrincipal();
        return CommonResult.success(user);
    }
}
