package com.isoler.studyim.business.user.model.bean;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableName;
import com.isoler.studyim.common.model.BaseEntity;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;

/**
 * <p>
 * 系统用户表
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-07-28
 */
@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
@TableName("db_chat.t_sys_user")
@ApiModel(value = "SysUser对象", description = "系统用户表")
public class SysUser extends BaseEntity {


    @ApiModelProperty(value = "登录id")
    @TableField("c_login_id")
    private String loginId;

    @ApiModelProperty(value = "用户名")
    @TableField("c_username")
    private String username;

    @ApiModelProperty(value = "密码")
    @TableField("c_password")
    private String password;

    @ApiModelProperty(value = "状态")
    @TableField("c_status")
    private String status;


}
