package com.isoler.studyim.business.chatmessage.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.isoler.studyim.business.chatmessage.model.bean.ChatMessage;

/**
 * <p>
 * 聊天消息 Mapper 接口
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-07-28
 */
public interface ChatMessageMapper extends BaseMapper<ChatMessage> {
    /**
     * 设置消息失效
     */
    Integer invalidMessage();
}
