package com.isoler.studyim.business.userroom.service.impl;

import com.isoler.studyim.business.userroom.model.bean.UserRoom;
import com.isoler.studyim.business.userroom.mapper.UserRoomMapper;
import com.isoler.studyim.business.userroom.service.IUserRoomService;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import org.springframework.stereotype.Service;

/**
 * <p>
 * 用户聊天室关联表 服务实现类
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-07-28
 */
@Service
public class UserRoomServiceImpl extends ServiceImpl<UserRoomMapper, UserRoom> implements IUserRoomService {

}
