package com.isoler.studyim.business.chatroom.controller;


import io.swagger.annotations.Api;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * <p>
 * 聊天室 前端控制器
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-07-28
 */

@RestController
@RequestMapping("chatRoom")
@Api(tags = "聊天室接口")
public class ChatRoomController {

}
