package com.isoler.studyim.business.userroom.mapper;

import com.isoler.studyim.business.userroom.model.bean.UserRoom;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;

/**
 * <p>
 * 用户聊天室关联表 Mapper 接口
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-07-28
 */
public interface UserRoomMapper extends BaseMapper<UserRoom> {

}
