package com.isoler.studyim.business.userroom.controller;


import org.springframework.web.bind.annotation.RequestMapping;

import org.springframework.web.bind.annotation.RestController;

/**
 * <p>
 * 用户聊天室关联表 前端控制器
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-07-28
 */
@RestController
@RequestMapping("userRoom")
public class UserRoomController {

}
