package com.isoler.studyim.business.user.mapper;

import com.isoler.studyim.business.user.model.bean.SysUser;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;

/**
 * <p>
 * 系统用户表 Mapper 接口
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-07-28
 */
public interface SysUserMapper extends BaseMapper<SysUser> {

}
