package com.isoler.studyim.business.filestorage.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.isoler.studyim.business.filestorage.model.bean.FileStorage;
import com.isoler.studyim.business.filestorage.model.dto.FileDownloadDto;
import com.isoler.studyim.business.filestorage.model.dto.FileUploadResultDto;
import org.springframework.web.multipart.MultipartFile;

/**
 * <p>
 * 服务类
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-10-02
 */
public interface IFileStorageService extends IService<FileStorage> {
    /**
     * 下载文件
     *
     * @param id
     * @return
     */
    FileDownloadDto downloadFile(String id);

    /**
     * 上传文件
     *
     * @param dto
     * @return
     */
    FileUploadResultDto uploadFile(MultipartFile file);

    /**
     * 删除文件
     *
     * @param id
     */
    void deleteFile(String id);
}
